### ISSUE TITLE
Installed using yeoman - why am I generating java files?

### ISSUE THREAD

**Issue by davetao** [androidstarters/kotlin-android-starter#1]
Hi,
Wondering why my generator is creating java files instead of .kt files. It is a fresh installation of yeoman and the generator.

<img width="1552" alt="screen shot 2017-06-04 at 11 54 10" src="https://cloud.githubusercontent.com/assets/4438069/26758266/9211a306-491c-11e7-8bb7-744d32fc05d1.png">

**Comment by ravidsrk** [comment]
@davetao Generator is still WIP. It is being developed here https://github.com/ravidsrk/generator-android-mvp-starter/tree/kotlin.

**Comment by ravidsrk** [comment]
@davetao I have fixed the generator now. It generates Kotlin sample now.
