### ISSUE TITLE
Moshi

### ISSUE THREAD

**Issue by sylflo** [androidstarters/kotlin-android-starter#13]
Thank you, for the boilerplate, really awesome work :).
Is it possible to make a pull request to replace Gson by Moshi ? Or maybe have it on another branch

**Comment by ravidsrk** [comment]
@sylflo Please open the PR. I was thinking to replace Gson by Moshi.

**Comment by ravidsrk** [comment]
Closed though https://github.com/androidstarters/kotlin-android-starter/pull/15

**Comment by ravidsrk** [comment]
Thanks, @sylflo for contribution.
