### ISSUE TITLE
Boilerplate looks a little heavy

### ISSUE THREAD

**Issue by humblerookie** [androidstarters/kotlin-android-starter#17]
While the project consists of a really good collection of libraries, It seems we could have a leaner version.
Wouldn't it be a better idea to have a core/lite branch that houses only the essentials and leaves out stuff like sherlock, sqlbrite, chuck etc. which are really a very subjective lot?

**Comment by shivam0x** [comment]
@humblerookie Thanks for the feedback. We have a lite version of MVP Starter in our roadmap which won't have all the heavy libs. But no ETA on that as of now.
