### ISSUE TITLE
Pokemon APIs now using captcha

### ISSUE THREAD

**Issue by jboxx** [androidstarters/kotlin-android-starter#19]
Currently these APIs using captcha, so we cannot get pokemon data.

**Comment by ravidsrk** [comment]
@jboxx Are you aware of changes required to make it work?

**Comment by iffanmajid** [comment]
Not all location affected the captcha, IP from Indonesia is one of them. Retrofit returns 403 forbidden

**Comment by derohimat** [comment]
I'm from Indonesia and can't load that data without checklist the captcha and just create an issue here

https://github.com/androidstarters/kotlin-android-starter/issues/33

**Comment by iffanmajid** [comment]
@derohimat have you ever tried it with VPN?

**Comment by derohimat** [comment]
@iffanmajid yes, solved by VPN yesterday afternoon.
