### ISSUE TITLE
generator downloads old version!

### ISSUE THREAD

**Issue by AhmedVargos** [androidstarters/kotlin-android-starter#34]
The  yeoman generator using the "yo kotlin-android" command generates an old version of the project, not the latest as in the repo with moshi and newer versions.

**Comment by ravidsrk** [comment]
@AhmedVargos I will sync the latest code today. Thanks

**Comment by AhmedVargos** [comment]
@ravidsrk  Great will be waiting for it. Thanks

**Comment by ravidsrk** [comment]
@AhmedVargos Synced
